# Basic Python


**TASK 1**

In [1]:

def conversion(conversion_type, value):
    """
    Converts a given value based on the specified conversion type.

    This function allows the user to choose a unit for conversion
    based on the given conversion type (length, volume, or weight)
    and prints the converted value.

    Parameters:
        conversion_type (str): The type of conversion. Options: 'length', 'volume', or 'weight'.
        value (float): The numerical value to be converted.

    Returns:
        None
    """
    match conversion_type:
        case 'length':
            unit = input("Convert from (m to ft / ft to m): ").strip().lower()
            if unit == "m to ft":
                print(f"{value} meters is {value * 3.28084} feet")
            elif unit == "ft to m":
                print(f"{value} feet is {value / 3.28084} meters")
            else:
                print("Invalid length conversion type.")

        case 'volume':
            unit = input("Convert from (L to gal / gal to L): ").strip().lower()
            if unit == "l to gal":
                print(f"{value} liters is {value * 0.264172} gallons")
            elif unit == "gal to l":
                print(f"{value} gallons is {value / 0.264172} liters")
            else:
                print("Invalid volume conversion type.")

        case 'weight':
            unit = input("Convert from (kg to lbs / lbs to kg): ").strip().lower()
            if unit == "kg to lbs":
                print(f"{value} kg is {value * 2.20462} pounds")
            elif unit == "lbs to kg":
                print(f"{value} pounds is {value / 2.20462} kg")
            else:
                print("Invalid weight conversion type.")

        case _:
            print("Invalid conversion category.")


try:
    type_list = ('length', 'volume', 'weight')
    conversion_type = input("Enter a conversion type (Length, Weight, or Volume): ").strip().lower()

    if conversion_type not in type_list:
        print("Invalid Conversion type. Program Ended!")
    else:
        value = float(input("Enter the value to be converted: "))
        if value < 0:
            raise ValueError()
        conversion(conversion_type, value)

except ValueError:
    print("Only positive numeric values are allowed.")


Enter a conversion type (Length, Weight, or Volume): length
Enter the value to be converted: 50
Convert from (m to ft / ft to m): m to ft
50.0 meters is 164.042 feet


**TASK 2**

In [4]:
def list_operations(user_list: list[int], operation_type: str) -> int | float:
    """
    Performs mathematical operations on a list of numbers based on the operation type.

    This function allows the user to define a list of numbers and choose an operation
    type to perform (Sum, Avg, Maximum, or Minimum) and returns the computed value.

    Parameters:
        user_list (list[int]): The list of numbers inputted by the user.
        operation_type (str): The type of operation to perform.
                            Options: 'sum', 'avg', 'maximum', or 'minimum'.

    Returns:
        result (int | float): The computed result.
    """
    match operation_type:
        case 'sum':
            total = 0
            for num in user_list:
                total += num
            return total

        case 'avg':
            total = 0
            count = 0
            for num in user_list:
                total += num
                count += 1
            return total / count if count > 0 else 0

        case 'maximum':
            max_value = user_list[0]
            for num in user_list:
                if num > max_value:
                    max_value = num
            return max_value

        case 'minimum':
            min_value = user_list[0]
            for num in user_list:
                if num < min_value:
                    min_value = num
            return min_value

        case _:
            return "Invalid operation type."

try:
    operation_types = ['sum', 'avg', 'maximum', 'minimum']

    user_list = input("Enter the list of numbers separated by spaces: ").split()
    formatted_list = [int(x) for x in user_list]

    operation = input("Select an operation to perform (sum, avg, maximum, minimum): ").lower()

    if operation not in operation_types:
        print("Invalid operation type.")
    else:
        result = list_operations(formatted_list, operation)
        print(f'Result of {operation} in the list {formatted_list} is {result}')

except ValueError:
    print("Invalid input. Please enter only numeric values separated by spaces.")


Enter the list of numbers separated by spaces: 1 2 3 4 5 6 7 8 9 10
Select an operation to perform (sum, avg, maximum, minimum): sum
Result of sum in the list [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] is 55


In [44]:

def extract_every_other(lst):
  """
    Extracts every other element from the given list.

    Args:
        lst (list): The input list.

    Returns:
        list: A new list containing every other element from the original list, starting from index 0.
  """
  return lst[::2]

lst = [1, 2, 3, 4, 5, 6,18]
lst2=extract_every_other(lst)
print(lst2)


[1, 3, 5, 18]


In [29]:
def reverse_list(lst):
  """
    reverses the given list using slicing.

    Args:
        lst (list): The input list.

    Returns:
        list: A reveresed list of the input list.
  """
  return lst[::-1]

lst = [1, 2, 3, 4, 5, 6]
lst2=reverse_list(lst)
print(lst2)

[6, 5, 4, 3, 2, 1]


In [33]:
def remove_first_last(lst):
  """
    removes the first and last elements of the given list using slicing.

    Args:
        lst (list): The input list.

    Returns:
        list: A list without firts and last element of the input list.
  """
  return lst[1:-1]
lst = [1, 2, 3, 4, 5, 6]
lst1= remove_first_last(lst)
print(lst1)

[2, 3, 4, 5]


In [35]:
def get_first_n(lst, n):
  """
    returns the first n elements of the given list using slicing.

    Args:
        lst (list): The input list.
        n (int): The number of elements to return.

    Returns:
        list: A list with n of first elements of the input list.
  """
  return lst[:n]
lst = [1, 2, 3, 4, 5, 6]
n = int (input(f"Enter the value for n ( must be less than or equal to {len(lst)})"))
lst1= get_first_n(lst,n)
print(lst1)

Enter the value for n ( must be less than or equal to 6)4
[1, 2, 3, 4]


In [40]:
def get_last_n(lst, n):
  """
    returns the last n elements of the given list using slicing.

    Args:
        lst (list): The input list.
        n (int): The number of elements to return.

    Returns:
        list: A list with n of last elements of the input list.
  """
  return lst[-n:]
lst = [1, 2, 3, 4, 5]
n = int (input(f"Enter the value for n ( must be less than or equal to {len(lst)})"))
lst1= get_last_n(lst,n)
print(lst1)

Enter the value for n ( must be less than or equal to 5)2
[4, 5]


In [45]:
def reverse_skip(lst):
    """
    Extracts every second element from the given list in reverse order.

    Args:
        lst (list): The input list.

    Returns:
        list: A new list containing every second element from the original list,
              starting from the second-to-last element.
    """
    return lst[-2::-2]

lst = [1, 2, 3, 4, 5, 6]
lst2=reverse_skip(lst)
print(lst2)

[5, 3, 1]


In [4]:
def flatten(nested_lst):
  return [item for lst in nested_lst for item in lst]

lst =[[1, 2], [3, 4], [5]]
flat_list = flatten(lst)
print(flat_list)

[1, 2, 3, 4, 5]


In [8]:
def access_nested_elements(lst,indices):
    result=lst
    for index in indices:
        result=result[index]
    return result
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1,2]
print(access_nested_elements(lst,indices))

6


In [12]:
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

nested_list = [[1, 2], [3, [4, 5]], 6]
print(sum_nested(nested_list))


21


In [13]:
def remove_element(lst,elem):
    new_lst =[]
    for item in lst:
        if isinstance(item, list):
            new_lst.append(remove_element(item,elem))
        elif item != elem:
            new_lst.append(item)
    return new_lst

lst = [[1, 2], [3, 2], [4, 5]]
elem = 2
print(remove_element(lst, elem))

[[1], [3], [4, 5]]


In [15]:
def find_max(lst):
    max = 0
    for item in lst:
        if isinstance(item, list):
            max = find_max(item)
        elif item > max:
            max = item
    return max

lst = [[1, 2], [3, [4, 5]], 6]
print(find_max(lst))



6


In [16]:
def count_occurences(lst,elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count = count + count_occurences(item,elem)
        elif item == elem:
            count += 1
    return count

lst = [[1, 2], [2, 3], [2, 4]]
elem = 2
print(count_occurences(lst, elem))


3


In [20]:
def deep_flatten(lst):
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))
        else:
            flat_list.append(item)
    return flat_list
lst = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print(deep_flatten(lst))

[1, 2, 3, 4, 5, 6, 7, 8]


In [26]:
def average_nested(lst):
    total = 0
    count = 0
    for sublist in lst:
        for num in sublist:
            total += num
            count += 1
    return total / count if count else 0
lst = [[1, 2], [3, 4], [5, 6]]
print(average_nested(lst))

3.5


# NUMPY

**Problem 1**

In [33]:
import numpy as np



In [29]:
empty_array = np.empty((2, 2))

ones_array = np.ones((4, 2))
print("Empty Array (2x2):\n", empty_array)
print('\n')
print("Ones Array (4x2):\n", ones_array)

Empty Array (2x2):
 [[4.53656086e-316 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]


Ones Array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [36]:
shape = (2,2)
fill_value = 8
filled_array = np.full(shape, fill_value)
print(f"array of given shape {shape} and type, filled with fill_value:{fill_value}\n {filled_array}")

array of given shape (2, 2) and type, filled with fill_value:8
 [[8 8]
 [8 8]]


In [40]:
array = np.array([[1, 2], [3, 4],[5,6]])
print(f"Given Array: {array}")
zeros_array = np.zeros_like(array)
print(f" Zero array :\n {zeros_array}")

ones_array = np.ones_like(array)
print(f" Ones array :\n {ones_array}")

Given Array: [[1 2]
 [3 4]
 [5 6]]
 Zero array :
 [[0 0]
 [0 0]
 [0 0]]
 Ones array :
 [[1 1]
 [1 1]
 [1 1]]


In [41]:
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print(f"Given List: {new_list}")
print(f"Numpy Array: {numpy_array}")

Given List: [1, 2, 3, 4]
Numpy Array: [1 2 3 4]


**Problem Two**

In [44]:
arr = np.arange(10,50)
print("Array from 10 to 49\n ",arr)


Array from 10 to 49
  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [45]:
arr = np.arange(0,9).reshape(3,3)
print("A 3x3 matrix with values from 0 to 8\n",arr)

A 3x3 matrix with values from 0 to 8
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [49]:
identity = np.eye(3)
print("3x3 identity matrix\n",identity)

3x3 identity matrix
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [50]:
random = np.random.random(30)
mean = random.mean()
print("Random Array of size 30:\n", random)
print("Mean of the array is\n",mean)

Random Array of size 30:
 [0.99134268 0.7428102  0.03666282 0.42205266 0.89638095 0.91938268
 0.0548192  0.19594313 0.42284752 0.13623791 0.77851951 0.69935983
 0.38031841 0.79211962 0.98222932 0.97468208 0.38236609 0.64246089
 0.36667815 0.93920618 0.33317317 0.42330717 0.13280159 0.71336971
 0.53436667 0.48028003 0.92261612 0.35074654 0.87186587 0.47959011]
Mean of the array is
 0.5666178930370164


In [51]:
random_arr = np.random.random((10, 10))
min = random_arr.min()
max = random_arr.max()
print("10X10 Array with random values:\n", random)
print("Minimum value:", min)
print("Maximum value:", max)


10X10 Array with random values:
 [0.99134268 0.7428102  0.03666282 0.42205266 0.89638095 0.91938268
 0.0548192  0.19594313 0.42284752 0.13623791 0.77851951 0.69935983
 0.38031841 0.79211962 0.98222932 0.97468208 0.38236609 0.64246089
 0.36667815 0.93920618 0.33317317 0.42330717 0.13280159 0.71336971
 0.53436667 0.48028003 0.92261612 0.35074654 0.87186587 0.47959011]
Minimum value: 0.0016236592690233032
Maximum value: 0.9794200758637359


In [53]:
zero_arr = np.zeros(10)
zero_arr[4] = 1
print("Zero Array with 5th element replaced with 1:\n", zero_arr)

Zero Array with 5th element replaced with 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [54]:
arr = [1,2,0,0,4,0]
print("Reversed:\n",arr[::-1])

Reversed:
 [0, 4, 0, 0, 2, 1]


In [56]:
arr1 = np.ones((7,7)).astype(int)
arr1[1:-1,1:-1]= 0
print("The array with ones in border and zero inside:\n",arr1)

The array with ones in border and zero inside:
 [[1 1 1 1 1 1 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 1 1 1 1 1 1]]


In [60]:

import numpy as np
board = np.ones((8, 8), dtype=int)

board[1::2, ::2] = 0
board[::2, 1::2] = 0

board


array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

# Problem 3


In [61]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])


In [62]:
add = x + y
print("Adding two array", add)

Adding two array [[ 6  8]
 [10 13]]


In [65]:
sub = x - y
print("Subtracting two array",sub)

Subtracting two array [[-4 -4]
 [-4 -3]]


In [66]:
multiply = x * 28
print("Mulyiplying x wiht 28", multiply)

Mulyiplying x wiht 28 [[ 28  56]
 [ 84 140]]


In [67]:
x2 = np.square(x)
print("Elements of x after squared",x2)

Elements of x after squared [[ 1  4]
 [ 9 25]]


In [68]:
dot_vw = v.dot(w)
dot_xv = x.dot(v)
dot_xy = x.dot(y)
print("Dot product of \n")
print(" v and w :\n",dot_vw)
print(" x and v :\n",dot_xv)
print(" x and y :\n",dot_xy)

Dot product of 

 v and w :
 219
 x and v :
 [29 77]
 x and y :
 [[19 22]
 [50 58]]


In [69]:

import numpy as np

xy_concatenated = np.concatenate((x, y), axis=0)
print("Concatenated x and y along rows:\n", xy_concatenated)

vw_concatenated = np.vstack((v, w))
print("\nConcatenated v and w along columns:\n", vw_concatenated)


Concatenated x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenated v and w along columns:
 [[ 9 10]
 [11 12]]


In [80]:
# xv_concatenated = np.concatenate((x,v),axis=1)
# xv_concatenated

#using concatenate throws an error, as concatenate requires both arrays to have same shape except the axis they are being concatenated on

#however, vstack works as it auto reshapes the arrays to match the shape
xv = np.vstack((x,v))
print("Concatenated x and v along columns:\n", xv)

Concatenated x and v along columns:
 [[ 1  2]
 [ 3  5]
 [ 9 10]]


**Problem 4**

In [82]:

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv).astype(int)
print("A.A−1 = I:\n", I)

AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:\n", AB)
print("BA:\n", BA)
print("AB != BA:", not np.array_equal(AB, BA))

AB_T = np.transpose(AB)
B_T = np.transpose(B)
A_T = np.transpose(A)
BT_AT = np.dot(B_T, A_T)

print("(AB)_T:\n", AB_T)
print("B_T.A_T:\n", BT_AT)
print("(AB)_T = B_T.A_T:", np.array_equal(AB_T, BT_AT))


A.A−1 = I:
 [[1 0]
 [0 0]]
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB != BA: True
(AB)_T:
 [[23 51]
 [13 29]]
B_T.A_T:
 [[23 51]
 [13 29]]
(AB)_T = B_T.A_T: True


In [83]:
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print("Solution:")
print("x =", X[0])
print("y =", X[1])
print("z =", X[2])


Solution:
x = 2.0
y = 1.0
z = -2.0


**EXPERIMENT**

In [2]:
import time
import numpy as np

size = 1000000

list1 = list(range(size))
list2 = list(range(size))

start_time = time.time()
list_sum = [x + y for x, y in zip(list1, list2)]
end_time = time.time()

print("Element-wise Addition (Lists):", end_time - start_time, "seconds")


array1 = np.arange(size)
array2 = np.arange(size)

start_time = time.time()
array_sum = array1 + array2
end_time = time.time()

print("Element-wise Addition (NumPy):", end_time - start_time, "seconds")



start_time = time.time()
list_product = [x * y for x, y in zip(list1, list2)]
end_time = time.time()

print("\nElement-wise Multiplication (Lists):", end_time - start_time, "seconds")


start_time = time.time()
array_product = array1 * array2
end_time = time.time()

print("Element-wise Multiplication (NumPy):", end_time - start_time, "seconds")




Element-wise Addition (Lists): 0.33856821060180664 seconds
Element-wise Addition (NumPy): 0.005872488021850586 seconds

Element-wise Multiplication (Lists): 0.10826253890991211 seconds
Element-wise Multiplication (NumPy): 0.004128694534301758 seconds


In [4]:
list_3 = list(range(size))
list_4 = list(range(size))


start_time = time.time()
dot_product_list = sum(x * y for x, y in zip(list_3, list_4))
end_time = time.time()
print("Dot Product (Lists):", end_time - start_time, "seconds")

array_a = np.arange(size)
array_b = np.arange(size)

start_time = time.time()
dot_product_array = np.dot(array_a, array_b)
end_time = time.time()
print("Dot Product (NumPy):", end_time - start_time, "seconds")



Dot Product (Lists): 0.16276979446411133 seconds
Dot Product (NumPy): 0.002066373825073242 seconds


In [8]:
size = 1000
A = [[np.random.randint(0, 10) for i in range(size)] for j in range(size)]
B = [[np.random.randint(0, 10) for i in range(size)] for j in range(size)]

start_time = time.time()
C = [[sum(A[i][k] * B[k][j] for k in range(size)) for j in range(size)] for i in range(size)]
end_time = time.time()

print("Matrix Multiplication (Lists):", end_time - start_time, "seconds")

A_np = np.array(A)
B_np = np.array(B)

start_time = time.time()
C_np = np.dot(A_np, B_np)
end_time = time.time()

print("Matrix Multiplication (NumPy):", end_time - start_time, "seconds")


Matrix Multiplication (Lists): 125.30932211875916 seconds
Matrix Multiplication (NumPy): 1.4548697471618652 seconds
